server {
    listen 80;

    location / {
        root /var/www/resume;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        # Здесь Nginx стучится в бэкенд локально внутри контейнера
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
